### ISSUE TITLE
erreur tempo

### ISSUE THREAD

**Issue by crocro81** [MyElectricalData/content-card-linky#13]
bonjour,

petit problème pour afficher tempo sur la carte 
mon code ; 
tempoInfo: sensor.edf_tempo_info
showTitle: true
showTempo: true
tempoEntityJ0: sensor.rte_tempo_today
tempoEntityJ1: sensor.rte_tempo_tomorrow

j'ai une erreur en affichage sur la carte  ; erreur ; sensor 'info' indisponible ou incorrecte

**Comment by rmb82** [comment]
Salut
J'ai la meme erreur
cela fonctionnait avec la carte saniho avant que je la désinstalle pour installer la MyElectricalData

![image](https://github.com/MyElectricalData/content-card-linky/assets/155725595/9e53f879-946f-4def-bebd-c5101f1b1752)

**Comment by rmb82** [comment]
Ah ben c'est dans l'dernier pull request : **Rename tempoInfo by tempoEntityInfo**

**Comment by vingerha** [comment]
tempoEntityInfo: sensor.edf_tempo_info
      tempoEntityJ0: sensor.rte_tempo_today
      tempoEntityJ1: sensor.rte_tempo_tomorrow
