### ISSUE TITLE
quel sensor pour affichage données ?

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/content-card-linky#17]
Bonjour,

J'ai quelques soucis de sensors pour afficher correctement les données linky.

J'utilise Linky 1911XXXXXXXXXX consumption : les données semblent erronées pour certaines

si j'utilise  Linky 1911XXXXXXXXXX myelectricaldata.1911XXXXXXXXXX : j'ai des erreurs de date certains jours.

si j'utilise sensor.myelectricaldata_123456XXXX : pas de données

Merci

**Comment by vingerha** [comment]
Sensor de base est nommé: sensor.linky_123456789_consumption
