### ISSUE TITLE
erreur : you need to define an entity ?

### ISSUE THREAD

**Issue by defaliz** [MyElectricalData/content-card-linky#18]
bonsoir,
désolé pour la question de débutant, mais je connais pas bien HA
j'ai bien installé myelectricaldata et j'importe bien les données
j'ai bien installé HACS et le bon dépot pour content-card-linky
lorsque je veux intégrer la carte j'ai l'erreur "you need to define an entity"
malheureusement je ne sais pas comment faire pour corriger ?
s'agit-il d'insérer les lignes dans un fichier yaml ?
 type: 'custom:content-card-linky'
entity: sensor.xxx_myelctricaldata_xxxx

merci de votre aide, dites moi où se trouve le bon forum pour ce genre de question.

**Comment by vingerha** [comment]
Il faut mettre dans la carte:
entity: sensor.linky_123456789_consumption
