### ISSUE TITLE
Plus de données de la veille depuis quelques jours

### ISSUE THREAD

**Issue by Jeepmg** [MyElectricalData/content-card-linky#20]
Bonjour @m4dm4rtig4n 

Depuis quelques jours, je ne reçois plus les données de la veille mais seulement les données de l'avant veille.

je n'ai rien modifié dans ma config HA.

J'ai fait un curl ce matin et résultat identiques, données du 25 mais pas du 26.

![image](https://github.com/MyElectricalData/content-card-linky/assets/103240876/1c26983f-a847-42e2-986f-d5a7e9cb5186)

![image](https://github.com/MyElectricalData/content-card-linky/assets/103240876/fd40be22-d136-4b5c-90e0-7c2e2ffdd71c)

**Comment by Jeepmg** [comment]
Ce matin ca me dit quota dépassé !

{
  "detail": "Vous avez dépassé votre quota journalier (50)"
}

**Comment by Jeepmg** [comment]
Mise à jour :

-Cela fait 2 jours que les données de la veille arrivent à 17h15. Problème de cache ?

**Comment by emilienarium** [comment]
Bonjour,
Je suis dans le même cas.
J'ai supprimé le cache local et le cache de la passerelle et ré importé les données.
Pas possbile d'avoir les données de la veille avant 17H15

**Comment by vingerha** [comment]
C'est pas liée avec la carte, je ferme ce issue
