### ISSUE TITLE
Icone Linky, plus disponible.

### ISSUE THREAD

**Issue by WarC0zes** [MyElectricalData/content-card-linky#4]
Bonjour,
depuis une semaine l'icone du linky sur la carte linky ne s'affiche plus. J'utilise la version 1.5.3 pour MED 0.9.1.

 https://apps.lincs.enedis.fr/mes-prms/assets/images/compteurs/linky.svg  
erreur: {"status":"500","error":"PROXY_SERVER_ERROR","message":"Internal Server Error"}

![linky not icon](https://github.com/MyElectricalData/content-card-linky/assets/91471397/1e4209c5-dfaa-4c59-87b0-553104c0d38d)

**Comment by WarC0zes** [comment]
Bonjour @vingerha,
merci pour le version v.1.5.3.1 qui rajoute une icone local. Mais la nouvelle icone a un fond blanc et est plus petite que l'ancienne. Sur un thème dark, ca ressort mal.

C'est possible d'enlever ce fond blanc et avoir une taille identique a l'ancienne icone ?

Nouvelle icone:
![carte linky icon local](https://github.com/MyElectricalData/content-card-linky/assets/91471397/5a0c5cc3-4c3a-4191-aeaf-35155d113fc9)

Acienne icone:
![enedis 04](https://github.com/MyElectricalData/content-card-linky/assets/91471397/9a542903-59fc-4976-8914-2a3b10e972f7)

**Comment by vingerha** [comment]
J'ai pas trouvé un icone pareil...si tu l'as, stp m'envoyer et (!) tu peux le faire toi même par copier un SVG dans le dossier 'icons' avec le même nom

**Comment by WarC0zes** [comment]
C'est bon pour toi, c'est icone ?
![logo-linky](https://github.com/MyElectricalData/content-card-linky/assets/91471397/11d4e95f-3cbd-4d2e-8d83-93153b78c2b6)

**Comment by vingerha** [comment]
mieux comme tu veux mas pas 100% (pour moi ça suffit)..voir les angles
![image](https://github.com/MyElectricalData/content-card-linky/assets/44190435/b0d01280-09cc-45b7-85e6-ac1981af003c)

**Comment by WarC0zes** [comment]
Ok, je referais un svg mais demain car je passe pas un service en ligne free et j'ai dépasser le quota lol.

**Comment by WarC0zes** [comment]
Encore plus simple, sur le site enedis a c'est adresse https://mon-compte-particulier.enedis.fr/compteur/ , il y a une icone svg ;)
![linky (1)](https://github.com/MyElectricalData/content-card-linky/assets/91471397/1b00dc41-f875-4b08-a3c5-d112295c6d6b)

**Comment by vingerha** [comment]
v1.5.4.b3

**Comment by WarC0zes** [comment]
Tu peu faire une 1.5.3.2 ?
J'utilise pas MED Dev, je suis en 0.9.1.

**Comment by vingerha** [comment]
Fixed and closed

**Comment by WarC0zes** [comment]
Merci beaucoup, au top !
